var OPTIFLOW_APP = Object.freeze({
  name: 'OPTIFLOW',
  timezone: 'Asia/Jakarta',
  version: '0.1.0',
});

var OPTIFLOW_REQUIRED_SHEETS = Object.freeze([
  'USER_ROLES',
  'ROLE_PERMISSIONS',
  'LINE_MASTER',
  'SHIFT_MASTER',
  'DEFECT_CATEGORIES',
  'RAW_LOGS',
  'QUARANTINE',
  'MASTER_RECAP',
  'DAILY_CLOSING',
  'ADJUSTMENT_LOGS',
  'AUDIT_LOGS',
]);

var OPTIFLOW_ROLES = Object.freeze([
  'Operator',
  'Mandor',
  'Management',
  'HRD',
  'SuperAdmin',
]);

var OPTIFLOW_AUTH_MODES = Object.freeze({
  ON: 'ON',
  OFF: 'OFF',
});

var OPTIFLOW_PERMISSION_CATALOG = Object.freeze({
  schema: Object.freeze(['bootstrap', 'read_health']),
  session: Object.freeze(['read']),
  production_report: Object.freeze(['create', 'read']),
  quarantine: Object.freeze(['read', 'approve', 'reject', 'request_correction']),
  daily_closing: Object.freeze(['create', 'read', 'reopen']),
  adjustment: Object.freeze(['create', 'read', 'approve', 'reject']),
  dashboard: Object.freeze(['read']),
  user_role: Object.freeze(['create', 'read', 'update', 'soft_delete']),
  script_property: Object.freeze(['read_status', 'update', 'rotate_secret']),
});

var OPTIFLOW_SHEET_SCHEMAS = Object.freeze({
  USER_ROLES: Object.freeze([
    'user_id',
    'email',
    'role',
    'nama_lengkap_encrypted',
    'nomor_telepon_encrypted',
    'phone_blind_index',
    'status_aktif',
    'is_deleted',
    'deleted_at',
    'last_login',
    'created_at',
    'updated_at',
  ]),
  ROLE_PERMISSIONS: Object.freeze([
    'permission_id',
    'role',
    'resource',
    'action',
    'is_allowed',
    'updated_at',
  ]),
  LINE_MASTER: Object.freeze([
    'line_id',
    'line_name',
    'area',
    'mandor_email',
    'status_aktif',
    'created_at',
    'updated_at',
  ]),
  SHIFT_MASTER: Object.freeze([
    'shift_id',
    'shift_name',
    'start_time',
    'end_time',
    'timezone',
    'status_aktif',
    'updated_at',
  ]),
  DEFECT_CATEGORIES: Object.freeze([
    'defect_category_id',
    'defect_name',
    'qcc_factor',
    'severity',
    'status_aktif',
    'updated_at',
  ]),
  RAW_LOGS: Object.freeze([
    'transaction_id',
    'device_timestamp',
    'server_received_at',
    'sync_type',
    'operator_email',
    'client_version',
    'factory_date',
    'line_id',
    'shift_id',
    'machine_id',
    'target_harian',
    'tandon',
    'perolehan_ok',
    'perolehan_reject',
    'defect_category_id',
    'defect_notes',
    'status',
  ]),
  QUARANTINE: Object.freeze([
    'quarantine_id',
    'transaction_id',
    'reason_code',
    'payload_json',
    'status',
    'reviewed_by',
    'reviewed_at',
    'notes',
  ]),
  MASTER_RECAP: Object.freeze([
    'recap_id',
    'factory_date',
    'operator_email',
    'line_id',
    'shift_id',
    'machine_id',
    'target_total',
    'tandon_total',
    'ok_total',
    'reject_total',
    'defect_rate',
    'top_defect_category_id',
    'generated_at',
  ]),
  DAILY_CLOSING: Object.freeze([
    'closing_id',
    'factory_date',
    'line_id',
    'shift_id',
    'status',
    'closed_by',
    'closed_at',
    'reopened_by',
    'reopened_at',
    'notes',
  ]),
  ADJUSTMENT_LOGS: Object.freeze([
    'adjustment_id',
    'source_transaction_id',
    'factory_date',
    'line_id',
    'shift_id',
    'adjustment_type',
    'delta_json',
    'reason',
    'status',
    'requested_by',
    'approved_by',
    'approved_at',
    'created_at',
  ]),
  AUDIT_LOGS: Object.freeze([
    'audit_id',
    'actor_email',
    'actor_role',
    'action',
    'entity_type',
    'entity_id',
    'metadata_json',
    'created_at',
  ]),
});
