var OPTIFLOW_APP = Object.freeze({
  name: 'OPTIFLOW',
  timezone: 'Asia/Jakarta',
  version: '0.1.0',
});

var OPTIFLOW_REQUIRED_SHEETS = Object.freeze([
  'USER_ROLES',
  'ROLE_PERMISSIONS',
  'EMPLOYEE_MASTER',
  'LINE_MASTER',
  'SHIFT_MASTER',
  'BAGIAN_MASTER',
  'ATTENDANCE_EVENTS',
  'ATTENDANCE_DAILY_RECAP',
  'ATTENDANCE_MONTHLY_RECAP',
  'TARGET_MASTER',
  'DEFECT_CATEGORIES',
  'RAW_LOGS',
  'QUARANTINE',
  'MASTER_RECAP',
  'DAILY_CLOSING',
  'ADJUSTMENT_LOGS',
  'AUDIT_LOGS',
]);

var OPTIFLOW_ROLES = Object.freeze([
  'Operator',
  'Mandor',
  'Supervisor',
  'Management',
  'HRD',
  'SuperAdmin',
]);

var OPTIFLOW_AUTH_MODES = Object.freeze({
  ON: 'ON',
  OFF: 'OFF',
});

var OPTIFLOW_PRODUCTION_LOGS = Object.freeze({
  conflict_window_minutes: 10,
  max_integer_value: 999999,
  max_defect_notes_length: 140,
});

var OPTIFLOW_QUARANTINE_REASONS = Object.freeze({
  MACHINE_OPERATOR_TIME_COLLISION: 'MACHINE_OPERATOR_TIME_COLLISION',
});

var OPTIFLOW_DEFAULT_DEFECT_CATEGORIES = Object.freeze([
  Object.freeze({
    defect_category_id: 'DEF-SOLDER-THIN',
    defect_name: 'Solder tipis',
    qcc_factor: 'Method',
    severity: 'MEDIUM',
    status_aktif: true,
  }),
  Object.freeze({
    defect_category_id: 'DEF-SOLDER-BRIDGE',
    defect_name: 'Solder bridge',
    qcc_factor: 'Machine',
    severity: 'HIGH',
    status_aktif: true,
  }),
  Object.freeze({
    defect_category_id: 'DEF-COMPONENT-MISS',
    defect_name: 'Komponen missing',
    qcc_factor: 'Material',
    severity: 'HIGH',
    status_aktif: true,
  }),
  Object.freeze({
    defect_category_id: 'DEF-VISUAL-SCRATCH',
    defect_name: 'Visual scratch',
    qcc_factor: 'Environment',
    severity: 'LOW',
    status_aktif: true,
  }),
  Object.freeze({
    defect_category_id: 'DEF-POLARITY-REVERSE',
    defect_name: 'Polaritas terbalik',
    qcc_factor: 'Man',
    severity: 'CRITICAL',
    status_aktif: true,
  }),
  Object.freeze({
    defect_category_id: 'DEF-COLD-SOLDER',
    defect_name: 'Cold solder',
    qcc_factor: 'Method',
    severity: 'HIGH',
    status_aktif: true,
  }),
]);

var OPTIFLOW_DEFAULT_BAGIAN_MASTER = Object.freeze([
  Object.freeze({
    bagian_id: 'SOLDER',
    bagian_name: 'Bagian Solder',
    description: 'Proses solder/las komponen produksi.',
    unit_rate: 94,
    monthly_target_unit: 37234,
    target_salary: 3500000,
    status_aktif: true,
  }),
  Object.freeze({
    bagian_id: 'LEM',
    bagian_name: 'Bagian Lem',
    description: 'Proses lem dan perakitan lanjutan.',
    unit_rate: 83,
    monthly_target_unit: 42169,
    target_salary: 3500000,
    status_aktif: true,
  }),
  Object.freeze({
    bagian_id: 'PACKING',
    bagian_name: 'Bagian Packing',
    description: 'Packing dan persiapan pengiriman.',
    unit_rate: 0,
    monthly_target_unit: 0,
    target_salary: 3500000,
    status_aktif: true,
  }),
]);

var OPTIFLOW_PERMISSION_CATALOG = Object.freeze({
  schema: Object.freeze(['bootstrap', 'read_health']),
  session: Object.freeze(['read']),
  production_report: Object.freeze(['create', 'read']),
  quarantine: Object.freeze(['read', 'approve', 'reject', 'request_correction']),
  daily_closing: Object.freeze(['create', 'read', 'reopen']),
  adjustment: Object.freeze(['create', 'read', 'approve', 'reject']),
  production_review: Object.freeze(['read', 'void', 'request_correction', 'pre_closing_correction']),
  audit_log: Object.freeze(['read']),
  dashboard: Object.freeze(['read']),
  defect_category: Object.freeze(['read', 'create', 'update', 'soft_delete', 'seed']),
  bagian_master: Object.freeze(['read', 'create', 'update', 'soft_delete', 'seed']),
  production_target: Object.freeze(['read', 'create', 'update', 'bulk_update', 'soft_delete']),
  employee_master: Object.freeze(['read', 'create', 'update', 'soft_delete']),
  attendance_recap: Object.freeze(['read', 'export']),
  reference_data: Object.freeze(['read']),
  test_runner: Object.freeze(['run']),
  user_role: Object.freeze(['create', 'read', 'update', 'soft_delete']),
  script_property: Object.freeze(['read_status', 'update', 'delete', 'rotate_secret']),
});

var OPTIFLOW_SCRIPT_PROPERTY_CONTRACT = Object.freeze({
  AUTH_MODE: Object.freeze({
    sensitivity: 'CONFIG',
    readable: true,
    updatable: true,
    deletable: false,
    rotatable: false,
    allowed_values: Object.freeze(['ON', 'OFF']),
  }),
  APP_ACTIVE_UNTIL: Object.freeze({
    sensitivity: 'CONFIG',
    readable: true,
    updatable: true,
    deletable: true,
    rotatable: false,
    pattern: '^\\d{4}-\\d{2}-\\d{2}$',
  }),
  REQUIRE_REGISTERED_EMAIL_LOGIN: Object.freeze({
    sensitivity: 'CONFIG',
    readable: true,
    updatable: true,
    deletable: true,
    rotatable: false,
    allowed_values: Object.freeze(['TRUE', 'FALSE']),
  }),
  SPREADSHEET_ID: Object.freeze({
    sensitivity: 'CONFIG',
    readable: true,
    updatable: true,
    deletable: true,
    rotatable: false,
    pattern: '^[A-Za-z0-9_-]{20,}$',
  }),
  ENCRYPTION_SALT: Object.freeze({
    sensitivity: 'SECRET',
    readable: false,
    updatable: false,
    deletable: false,
    rotatable: true,
  }),
});

var OPTIFLOW_SHEET_SCHEMAS = Object.freeze({
  USER_ROLES: Object.freeze([
    'user_id',
    'email',
    'role',
    'nama_lengkap_encrypted',
    'nomor_telepon_encrypted',
    'phone_blind_index',
    'status_aktif',
    'is_deleted',
    'deleted_at',
    'last_login',
    'created_at',
    'updated_at',
    'username',
    'alamat_encrypted',
    'profile_base64',
    'mandor_email',
  ]),
  ROLE_PERMISSIONS: Object.freeze([
    'permission_id',
    'role',
    'resource',
    'action',
    'is_allowed',
    'updated_at',
  ]),
  EMPLOYEE_MASTER: Object.freeze([
    'employee_id',
    'employee_no',
    'nama_lengkap',
    'bagian_id',
    'status_karyawan',
    'email',
    'no_wa',
    'alamat',
    'username',
    'role',
    'roles',
    'mandor_email',
    'created_at',
    'updated_at',
  ]),
  ATTENDANCE_EVENTS: Object.freeze([
    'attendance_event_id',
    'factory_date',
    'employee_id',
    'event_type',
    'event_timestamp',
    'source',
    'notes',
    'created_by',
    'created_at',
  ]),
  ATTENDANCE_DAILY_RECAP: Object.freeze([
    'daily_attendance_id',
    'factory_date',
    'employee_id',
    'employee_no',
    'nama_lengkap',
    'bagian_id',
    'attendance_status',
    'clock_in_at',
    'clock_out_at',
    'confirmed_by',
    'confirmed_at',
    'notes',
    'payroll_ready',
    'updated_at',
  ]),
  ATTENDANCE_MONTHLY_RECAP: Object.freeze([
    'monthly_attendance_id',
    'period_month',
    'employee_id',
    'employee_no',
    'nama_lengkap',
    'bagian_id',
    'hadir_count',
    'izin_count',
    'sakit_count',
    'alpha_count',
    'resign_count',
    'pending_confirmation_count',
    'payroll_ready',
    'updated_at',
  ]),
  LINE_MASTER: Object.freeze([
    'line_id',
    'line_name',
    'area',
    'mandor_email',
    'status_aktif',
    'created_at',
    'updated_at',
  ]),
  SHIFT_MASTER: Object.freeze([
    'shift_id',
    'shift_name',
    'start_time',
    'end_time',
    'timezone',
    'status_aktif',
    'updated_at',
  ]),
  BAGIAN_MASTER: Object.freeze([
    'bagian_id',
    'bagian_name',
    'description',
    'unit_rate',
    'monthly_target_unit',
    'target_salary',
    'status_aktif',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
  ]),
  TARGET_MASTER: Object.freeze([
    'target_id',
    'factory_date',
    'effective_from',
    'effective_until',
    'line_id',
    'shift_id',
    'machine_id',
    'operator_email',
    'target_harian',
    'scope_type',
    'status_aktif',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
  ]),
  DEFECT_CATEGORIES: Object.freeze([
    'defect_category_id',
    'defect_name',
    'qcc_factor',
    'severity',
    'status_aktif',
    'updated_at',
  ]),
  RAW_LOGS: Object.freeze([
    'transaction_id',
    'device_timestamp',
    'server_received_at',
    'sync_type',
    'operator_email',
    'client_version',
    'factory_date',
    'line_id',
    'shift_id',
    'machine_id',
    'bagian_id',
    'work_category_id',
    'target_harian',
    'tandon',
    'perolehan_ok',
    'perolehan_reject',
    'defect_category_id',
    'defect_notes',
    'status',
  ]),
  QUARANTINE: Object.freeze([
    'quarantine_id',
    'transaction_id',
    'reason_code',
    'payload_json',
    'status',
    'reviewed_by',
    'reviewed_at',
    'notes',
  ]),
  MASTER_RECAP: Object.freeze([
    'recap_id',
    'factory_date',
    'operator_email',
    'line_id',
    'shift_id',
    'machine_id',
    'target_total',
    'tandon_total',
    'ok_total',
    'reject_total',
    'defect_rate',
    'top_defect_category_id',
    'generated_at',
  ]),
  DAILY_CLOSING: Object.freeze([
    'closing_id',
    'factory_date',
    'line_id',
    'shift_id',
    'status',
    'closed_by',
    'closed_at',
    'reopened_by',
    'reopened_at',
    'notes',
  ]),
  ADJUSTMENT_LOGS: Object.freeze([
    'adjustment_id',
    'source_transaction_id',
    'factory_date',
    'line_id',
    'shift_id',
    'adjustment_type',
    'delta_json',
    'reason',
    'status',
    'requested_by',
    'approved_by',
    'approved_at',
    'created_at',
  ]),
  AUDIT_LOGS: Object.freeze([
    'audit_id',
    'actor_email',
    'actor_role',
    'action',
    'entity_type',
    'entity_id',
    'metadata_json',
    'created_at',
  ]),
});
